version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export GITHASH=$(echo ${CIRCLE_SHA1} | cut -c -7)'
            echo 'export TAG=dev-0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update 
      
      - run:
          name: Build and push Docker image
          command: |
            GITHASH=$(echo ${CIRCLE_SHA1} | cut -c -7)
            echo ${GITHASH}
            docker build --build-arg tag=$GITHASH  -t malariagen/datalab:$GITHASH .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push malariagen/datalab:$GITHASH
workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master
